FROM centos:7

USER root
RUN yum install epel-release yum-utils -y
RUN yum install nginx -y
RUN mkdir /var/run/php-fpm 
RUN yum-config-manager --enable remi-php72
RUN yum --enablerepo=remi,remi-php72 install php-fpm php-common -y
RUN mkdir -p /etc/nginx/ssl
#COPY /nginx.conf /etc/nginx/nginx.conf
COPY /ssl/* /etc/nginx/ssl/
COPY /conf.d/* /etc/nginx/conf.d/

RUN sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/' /etc/php.ini
RUN sed -i 's/user = apache/user = nginx/' /etc/php-fpm.d/www.conf
RUN sed -i 's/group = apache/group = nginx/' /etc/php-fpm.d/www.conf
RUN sed -i 's/;listen.owner = nobody/listen.owner = nginx/' /etc/php-fpm.d/www.conf
RUN sed -i 's/;listen.group = nobody/listen.group = nginx/' /etc/php-fpm.d/www.conf
RUN sed -i 's/listen = 127.0.0.1:9000/listen = \/var\/run\/php-fpm\/php-fpm.sock/' /etc/php-fpm.d/www.conf
RUN sed -i 's/\/var\/log\/php-fpm\/www-error.log/\/usr\/local\/log\/php-fpm\/www-error.log/' /etc/php-fpm.d/www.conf


COPY /entrypoint.sh /usr/sbin/
RUN chmod +x /usr/sbin/entrypoint.sh
COPY /www/. /var/www/
RUN mkdir -p /usr/local/log/nginx
RUN mkdir -p /usr/local/log/php-fpm
RUN chown -R nginx:nginx /var/www

ENTRYPOINT ["/usr/sbin/entrypoint.sh"]
