FROM centos:7

USER root
RUN yum install -y epel-release yum-utils gcc openssl-devel readline-devel systemd-devel make pcre-devel
RUN curl http://www.haproxy.org/download/2.1/src/haproxy-2.1.0.tar.gz > haproxy-2.1.0.tar.gz
RUN tar xf haproxy-2.1.0.tar.gz
RUN curl https://www.lua.org/ftp/lua-5.3.5.tar.gz > lua-5.3.5.tar.gz
RUN tar xf lua-5.3.5.tar.gz
RUN cd lua-5.3.5 && make INSTALL_TOP=/opt/lua-5.3.5 linux install
RUN cd haproxy-2.1.0 && make USE_NS=1 \
    USE_TFO=1 \
    USE_OPENSSL=1 \
    USE_ZLIB=1 \
    USE_LUA=1 \
    USE_PCRE=1 \
    USE_SYSTEMD=1 \
    USE_LIBCRYPT=1 \
    USE_THREAD=1 \
    TARGET=linux-glibc \
    LUA_INC=/opt/lua-5.3.5/include \
    LUA_LIB=/opt/lua-5.3.5/lib && make PREFIX=/opt/haproxy install
RUN groupadd -g 188 haproxy
RUN useradd -g 188 -u 188 -d /var/lib/haproxy -s /sbin/nologin -c haproxy haproxy
COPY /haproxy.service /etc/systemd/system/haproxy.service
COPY /haproxy /etc/sysconfig/haproxy
COPY /haproxy.cfg /etc/haproxy/haproxy.cfg
ENTRYPOINT [ "/opt/haproxy/sbin/haproxy", "-d", "-f", "/etc/haproxy/haproxy.cfg" ]